### PR TITLE
(SERVER-3167) Pin jnr components to versions compiled with a glibc available on EL 7 linuxes

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
WIP. This allows Puppet Server to start on EL 7 linuxes but does not resolve all of the ffi issues.

**Comment by justinstoller** [comment]
Puppet Server 7.9.4.SNAPSHOT.2023.01.30T1427 was built with this.

**Comment by justinstoller** [comment]
Puppet Server 7.9.4.SNAPSHOT.2023.02.02T1022 also has this change and is built against some PE platforms for additional smoke testing.

**Comment by justinstoller** [comment]
I've validated a build of Puppet Server with these changes across our supported platforms in the linked Puppet Server PR.

**Comment by justinstoller** [comment]
I think this is ready to go

**Review by donoghuc — APPROVED** [review]

**Pull request merged**
