### PR TITLE
(SERVER-3007) Update Jruby to 9.2.17.0

### PR DESCRIPTION
**Pull request by Magisus**
This is a maintenance update.

### CODE REVIEW

**Comment by Magisus** [comment]
I tested this up through puppetserver and pe-pse. Will make sure orch tests with it when I go to bump jruby-utils in clj-parent. But no issues in our projects.

**Comment by Magisus** [comment]
@justinstoller is there benchmarking you do with these? I'd be interested in learning what you usually do there.

**Comment by justinstoller** [comment]
I usually run the full_catalog benchmark with 100 iterations a run.

**Comment by Magisus** [comment]
That's in Puppet?

**Review by mwaggett — APPROVED** [review]

**Comment by Magisus** [comment]
Benchmarks came out about the same as 9.2.14.

**Pull request merged**
