### PR TITLE
(SERVER-3133) Update JRuby to 9.3.4.0

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by mwaggett** [comment]
If we're not bumping 6.x, I think we need to branch this repo.

**Comment by Magisus** [comment]
I was planning to wait to branch until we _need_ to bump 6.x in a way that isn't backporting this update. We can do a 9.2.x off of the tag before this update if needed, given that the repo is versioned after the version of JRuby it contains.

**Comment by mwaggett** [comment]
okay. Mostly I just didn't want us to _accidentally_ bump in 6.x, if we needed to make a different update. but if you think we won't, that's fine.

**Comment by Magisus** [comment]
I think we probably need to branch the stuff downstream of this. But this one I'm okay leaving for now I think.

**Comment by Magisus** [comment]
I think this can land now?

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
