### PR TITLE
(maint) Take up 9.2.14.0

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
still running tests

**Review by mwaggett — APPROVED** [review]
This is just for keeping up-to-date, right? No security content or new functionality we need?

**Comment by Magisus** [comment]
Huh, there's an `invokedynamic` optimization in there. Wonder if that would help us at all. I seem to remember we had to turn it off...

**Review by Magisus — APPROVED** [review]

**Comment by justinstoller** [comment]
This updates webrick for a cve, however we don't use webrick.
I'm also interested in the optimization, but we've also gotten bit by their optimizations in the past. I've successfully ran the puppetserver tests locally with this change, but I also want to run some of Puppet's benchmarks on this jruby first.

**Comment by justinstoller** [comment]
Ran the puppet benchmarks with this version and things look fine:
```
 (main *%<>) :: ruby --version
jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.8+11 on 11.0.8+11 +jit [darwin-x86_64]

 (main *%<>) :: ITERATIONS=100 be rake benchmark:full_catalog
....
Run 99     /var/folders/8t/njts_3s96_v6f30y1b8b92c00000gn/T/full_catalog20201209-52617-gl2z7x/environments/perf_control/modules/influxdb/templates/influxdb.conf.erb:223: warning: constant ::Fixnum is deprecated                                        
  2.660000   0.080000   2.740000 (  2.470954)                                                                                
  Run 100    /var/folders/8t/njts_3s96_v6f30y1b8b92c00000gn/T/full_catalog20201209-52617-gl2z7x/environments/perf_control/modules/influxdb/templates/influxdb.conf.erb:223: warning: constant ::Fixnum is deprecated                                      
    2.520000   0.080000   2.600000 (  2.183365)                                                                              
    > total:   371.640000  10.460000 382.100000 (245.296344)                                                                 
    > avg:       3.716400   0.104600   3.821000 (  2.452963)
```
vs
```
 (main *%<>) :: ruby --version
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 11.0.8+11 on 11.0.8+11 +jit [darwin-x86_64]

 (main *%<>) :: ITERATIONS=100 be rake benchmark:full_catalog
....
Run 99     /var/folders/8t/njts_3s96_v6f30y1b8b92c00000gn/T/full_catalog20201209-53564-1xbq453/environments/perf_control/modules/influxdb/templates/influxdb.conf.erb:223: warning: constant ::Fixnum is deprecated                                       
  2.250000   0.080000   2.330000 (  2.176078)                                                                                
Run 100    /var/folders/8t/njts_3s96_v6f30y1b8b92c00000gn/T/full_catalog20201209-53564-1xbq453/environments/perf_control/modules/influxdb/templates/influxdb.conf.erb:223: warning: constant ::Fixnum is deprecated                                       
  2.470000   0.080000   2.550000 (  2.192485)                                                                                
> total:   373.030000  11.030000 384.060000 (235.170690)                                                                     
> avg:       3.730300   0.110300   3.840600 (  2.351707) 
```

I don't know that the difference is meaningful, but it bodes well that we're not causing a regression at least.

**Review by Magisus — APPROVED** [review]

**Pull request merged**
